### ISSUE TITLE
Link to documentation

### ISSUE THREAD

**Issue by AlexKnauth** [lexi-lambda/racket-alexis-collections#7]
Right now, the documentation link points to a page without a search field.
But the pages on pkg-bulid.racket-lang.org do have search fields.
http://pkg-build.racket-lang.org/doc/alexis-collections/index.html
http://pkg-build.racket-lang.org/doc/alexis-collections/collections-intro.html
Would it be better to link to one of those instead?

**Comment by lexi-lambda** [comment]
I'm not sure. I used to link to the pkg-build docs, but I switched to self-hosting so that the docs would be up-to-date with master. Admittedly, I think that they're currently out of sync, but I was considering using my CI docs deployment from alexis-collection-lens on this package, which would ensure they're always up to date.

**Comment by AlexKnauth** [comment]
The pkg-build docs update every day though, so you can never forget to update it.

**Comment by lexi-lambda** [comment]
Well, I believe they always use the current Racket release, not HEAD, and I have some version exceptions. Am I wrong about that?

**Comment by AlexKnauth** [comment]
Oh I hadn't realized.

**Comment by AlexKnauth** [comment]
Does that include a search field? Because that's what made me go find the pkg-build version.

**Comment by lexi-lambda** [comment]
No, it doesn't... and it probably can't, since it's not full-installation docs, just docs from a specific scribble file. Search _is_ a good feature, though. I'll consider changing the link in the README to include both links.
